#!/bin/bash   
echo "This script will set up Laravel on a Koding vm...";
echo "Updating currently installed packages";
sudo apt-get update;
echo "Installing Composer";
cd ~;
wget https://getcomposer.org/installer;
mkdir envi;
mv installer ./envi/installer;
cd envi;
php installer;
mv composer.phar composer;
echo "export PATH=$PATH:~/envi" >> ~/.bashrc;
source ~/.bashrc;
echo "Installing Laravel";
composer global require "laravel/installer";
echo "export PATH=$PATH:~/.composer/vendor/bin" >> ~/.bashrc;
source ~/.bashrc;
cd ~;
echo "Done";
echo "Try laravel new <project name>";
